spring:
  application:
    name: llm-microservice-observability-demo

llm:
  provider: ollama

langchain4j:
  ollama:
    chat-model:
      base-url: http://localhost:11434
      model-name: llama3.2
      temperature: 0.2

logging:
  level:
    root: DEBUG