receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
processors:
  batch:
    send_batch_size: 50
    timeout: 30s
exporters:
  otlphttp/langfuse:
    endpoint: ${LANGFUSE_BASE_URL}
    traces_endpoint: ${LANGFUSE_TRACES_URL}
    compression: gzip
    timeout: 30s
    headers:
      Authorization: "Basic ${LANGFUSE_BASIC_AUTH}"
    tls:
      insecure: true
    sending_queue:
      enabled: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/langfuse]